# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('idc', models.CharField(blank=True, max_length=30, null=True)),
                ('port', models.IntegerField(default='22')),
                ('os', models.CharField(default='linux', max_length=20, verbose_name='Operating System')),
            ],
        ),
    ]
