# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-05 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='server',
            new_name='Servers',
        ),
    ]
