# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20160405_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='idc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
