# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-11 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20160405_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
